#!/usr/bin/env python3
import soundfile as sf
import numpy as np
from scipy.ndimage import imread
import matplotlib.pyplot as plt
from scipy import signal
import time
import sys

def channel_to_image(channel, sample_rate, width = 800, height = 600):

    freq_increments = (sample_rate//2) // height

    frequencies, times, spectrogram = signal.spectrogram(channel, sample_rate)

    spectrogram = spectrogram / spectrogram.max() * 10000

    plt.pcolormesh(times, frequencies, spectrogram)
    plt.ylabel('Frequency [Hz]')
    plt.xlabel('Time [sec]')
    plt.show()

    

    
    return

samples, sample_rate = sf.read('output.wav')
samples = samples.transpose(1,0)

red = samples[0]
blue = samples[1]
green = samples[2]

channel_to_image(blue, sample_rate)